"""Registry for managing and executing metric providers."""

from typing import TYPE_CHECKING, Any

from app.planning.providers.activity import ActivityProvider
from app.planning.providers.ftp_trajectory import FTPTrajectoryProvider
from app.planning.providers.pmc import PMCProvider
from app.planning.providers.power_curve import PowerCurveProvider
from app.planning.providers.resting_hr import RestingHRTrendProvider
from app.planning.providers.wellness import WellnessProvider

if TYPE_CHECKING:
    import polars as pl

    from app.intervals.client import IntervalsClient
    from app.planning.providers.interfaces import DashboardWidget, MetricProvider


class MetricRegistry:
    """Registry that holds all active metric providers."""

    def __init__(self) -> None:
        """Initializes an empty registry."""
        self.providers: list[MetricProvider[Any]] = []

    def register(self, provider: MetricProvider[Any]) -> None:
        """Registers a new provider.

        Args:
            provider: The provider instance to register.
        """
        self.providers.append(provider)

    def process_analysis(
        self,
        daily_df: pl.DataFrame,
        client: IntervalsClient | None = None,
        display_days: int | None = None,
    ) -> tuple[dict[str, Any], list[DashboardWidget]]:
        """Run calculations for all providers and collect results/widgets.

        Args:
            daily_df: Polars DataFrame containing daily wellness/activity data.
            client: The Intervals.icu client.
            display_days: Optional number of days to display in widgets.

        Returns:
            tuple[dict[str, Any], list[DashboardWidget]]: A tuple containing:
                - dict[str, Any]: Mapping of provider names to their calculation results.
                - list[DashboardWidget]: List of dashboard widgets generated by the providers.
        """
        results: dict[str, Any] = {}
        widgets: list[DashboardWidget] = []
        for provider in self.providers:
            res = provider.calculate(
                daily_df,
                client=client,
                provider_results=results,
            )
            results[provider.get_name()] = res
            widget = provider.get_dashboard_widget(res, display_days=display_days)
            if widget:
                widgets.append(widget)
        return results, widgets

    async def get_combined_context(self, results: dict[str, Any]) -> str:
        """Collects and combines context from all registered providers.

        Args:
            results: Mapping of provider names to their calculation results.

        Returns:
            Combined context string from all providers.
        """
        contexts: list[str] = []
        for provider in self.providers:
            res = results.get(provider.get_name())
            if res is not None:
                context = await provider.provide_context(res)
                if context:
                    contexts.append(context)
        return "\n\n".join(contexts)


# Global registry instance
registry = MetricRegistry()
registry.register(ActivityProvider())
registry.register(WellnessProvider())
registry.register(PowerCurveProvider())
registry.register(RestingHRTrendProvider())
registry.register(FTPTrajectoryProvider())
registry.register(PMCProvider())
