"""Add user preferences.

Revision ID: 7543c1e4540b
Revises:
Create Date: 2026-04-22 12:38:31.351741

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "7543c1e4540b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("weekly_hours", sa.Float(), nullable=False, server_default="8.0"))
    op.add_column("user", sa.Column("weekly_sessions", sa.Integer(), nullable=False, server_default="4"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "weekly_sessions")
    op.drop_column("user", "weekly_hours")
    # ### end Alembic commands ###
